# Generated by Django 4.1 on 2024-09-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("salary", "Salary"),
                    ("business", "Business"),
                    ("investment", "Investment Returns"),
                    ("rental", "Rental Income"),
                    ("bonus", "Bonuses"),
                    ("gifts", "Gifts"),
                    ("other", "Other Income"),
                    ("housing", "Housing"),
                    ("utilities", "Utilities"),
                    ("groceries", "Groceries"),
                    ("transportation", "Transportation"),
                    ("healthcare", "Healthcare"),
                    ("insurance", "Insurance"),
                    ("debt", "Debt Payments"),
                    ("entertainment", "Entertainment"),
                    ("dining", "Dining Out"),
                    ("clothing", "Clothing"),
                    ("education", "Education"),
                    ("savings", "Savings"),
                    ("charity", "Charity"),
                    ("personal", "Personal Care"),
                    ("travel", "Travel"),
                    ("subscriptions", "Subscriptions"),
                    ("miscellaneous", "Miscellaneous"),
                ],
                max_length=50,
            ),
        ),
    ]
